language: elixir
elixir:
  - 1.6.6
otp_release:
  - 21.0.1
env:
  - MIX_ENV=test

jobs:
  include:
    - stage: unit tests
      script: mix coveralls.travis

    - stage: integration tests
      sudo: required
      services:
        - docker
      before_install:
        - cd integration
      script: mix test
